on: [push]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Execute Gradle build
        run: chmod +x gradlew && ./gradlew sonar

