  on: [push]
  jobs:
    sonarcloud:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Execute Gradle build
          run: chmod +x gradlew && ./gradlew sonar
