  on: [push]
  jobs:
    sonarcloud:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2.8.0
        - name: Execute Gradle build
          run: ./gradlew sonar
