  on: [push]
  jobs:
    sonarcloud:
      runs-on: ubuntu-latest
      steps:
        - uses: action/checkout@v4
          with:
            fetch-depth: 0
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
